server:
  port: 7777
spring:
  application:
    name: rabbit-demo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: hugh
    password: 123456
    virtual-host: /vhost_hugh
    listener:
      simple:
        acknowledge-mode: manual
        #初始连接数量
        concurrency: 5
        #最大连接数量
        max-concurrency: 10
        #限流
        prefetch: 1
        retry:
          max-attempts: 5
